/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) vde_adj_quadcopter_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[8] = {4, 1, 0, 4, 0, 1, 2, 3};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
#define s2 CASADI_PREFIX(s2)
/* adjFun */
int adjFun(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=5.0000000000000000e-01;
  real_t a1=arg[1] ? arg[1][3] : 0;
  real_t a2=(a0*a1);
  real_t a3=arg[0] ? arg[0][6] : 0;
  real_t a4=(a3*a2);
  real_t a5=arg[1] ? arg[1][2] : 0;
  real_t a6=(a0*a5);
  real_t a7=arg[0] ? arg[0][5] : 0;
  real_t a8=(a7*a6);
  a4=(a4+a8);
  a8=arg[1] ? arg[1][1] : 0;
  real_t a9=(a0*a8);
  real_t a10=arg[0] ? arg[0][4] : 0;
  real_t a11=(a10*a9);
  a4=(a4+a11);
  if (res[0]!=0) res[0][0]=a4;
  a4=(a0*a5);
  a11=(a3*a4);
  real_t a12=(a0*a1);
  real_t a13=(a7*a12);
  a11=(a11-a13);
  a13=arg[1] ? arg[1][0] : 0;
  real_t a14=(a0*a13);
  real_t a15=(a10*a14);
  a11=(a11-a15);
  if (res[0]!=0) res[0][1]=a11;
  a1=(a0*a1);
  a11=(a10*a1);
  a15=(a0*a8);
  real_t a16=(a3*a15);
  a11=(a11-a16);
  a16=(a0*a13);
  real_t a17=(a7*a16);
  a11=(a11-a17);
  if (res[0]!=0) res[0][2]=a11;
  a8=(a0*a8);
  a11=(a7*a8);
  a5=(a0*a5);
  a17=(a10*a5);
  a11=(a11-a17);
  a13=(a0*a13);
  a17=(a3*a13);
  a11=(a11-a17);
  if (res[0]!=0) res[0][3]=a11;
  a11=arg[1] ? arg[1][6] : 0;
  a17=(a7*a11);
  real_t a18=2.5000000000000000e-01;
  a17=(a18*a17);
  real_t a19=(a7*a11);
  a19=(a18*a19);
  a17=(a17-a19);
  a19=4.;
  real_t a20=arg[1] ? arg[1][5] : 0;
  a20=(a19*a20);
  real_t a21=(a3*a20);
  a21=(a18*a21);
  a17=(a17+a21);
  a21=(a3*a20);
  a17=(a17-a21);
  a21=arg[0] ? arg[0][2] : 0;
  a1=(a21*a1);
  a17=(a17+a1);
  a1=arg[0] ? arg[0][3] : 0;
  a5=(a1*a5);
  a17=(a17-a5);
  a5=arg[0] ? arg[0][0] : 0;
  a9=(a5*a9);
  a17=(a17+a9);
  a9=arg[0] ? arg[0][1] : 0;
  a14=(a9*a14);
  a17=(a17-a14);
  if (res[0]!=0) res[0][4]=a17;
  a17=(a18*a10);
  a17=(a17*a11);
  a14=(a18*a10);
  a14=(a14*a11);
  a17=(a17-a14);
  a14=arg[1] ? arg[1][4] : 0;
  a19=(a19*a14);
  a14=(a3*a19);
  a14=(a18*a14);
  a17=(a17-a14);
  a3=(a3*a19);
  a17=(a17+a3);
  a12=(a9*a12);
  a17=(a17-a12);
  a6=(a5*a6);
  a17=(a17+a6);
  a8=(a1*a8);
  a17=(a17+a8);
  a16=(a21*a16);
  a17=(a17-a16);
  if (res[0]!=0) res[0][5]=a17;
  a17=(a18*a10);
  a17=(a17*a20);
  a10=(a10*a20);
  a17=(a17-a10);
  a18=(a18*a7);
  a18=(a18*a19);
  a17=(a17-a18);
  a7=(a7*a19);
  a17=(a17+a7);
  a5=(a5*a2);
  a17=(a17+a5);
  a9=(a9*a4);
  a17=(a17+a9);
  a21=(a21*a15);
  a17=(a17-a21);
  a1=(a1*a13);
  a17=(a17-a1);
  if (res[0]!=0) res[0][6]=a17;
  a17=arg[2] ? arg[2][0] : 0;
  a1=(a17+a17);
  a11=(a0*a11);
  a13=9.2249999999999988e-03;
  a13=(a13*a11);
  a1=(a1*a13);
  a17=(a17+a17);
  a20=(a0*a20);
  a11=1.5375000000000000e-02;
  a20=(a11*a20);
  a17=(a17*a20);
  a1=(a1-a17);
  if (res[0]!=0) res[0][7]=a1;
  a1=arg[2] ? arg[2][1] : 0;
  a17=(a1+a1);
  a0=(a0*a19);
  a11=(a11*a0);
  a17=(a17*a11);
  a1=(a1+a1);
  a1=(a1*a13);
  a17=(a17-a1);
  if (res[0]!=0) res[0][8]=a17;
  a17=arg[2] ? arg[2][2] : 0;
  a1=(a17+a17);
  a1=(a1*a13);
  a17=(a17+a17);
  a17=(a17*a20);
  a1=(a1+a17);
  if (res[0]!=0) res[0][9]=a1;
  a1=arg[2] ? arg[2][3] : 0;
  a17=(a1+a1);
  a17=(a17*a13);
  a1=(a1+a1);
  a1=(a1*a11);
  a17=(a17+a1);
  a17=(-a17);
  if (res[0]!=0) res[0][10]=a17;
  return 0;
}

void adjFun_incref(void) {
}

void adjFun_decref(void) {
}

int adjFun_n_in(void) { return 3;}

int adjFun_n_out(void) { return 1;}

const char* adjFun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

const char* adjFun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const int* adjFun_sparsity_in(int i) {
  switch (i) {
    case 0: return s0;
    case 1: return s0;
    case 2: return s1;
    default: return 0;
  }
}

const int* adjFun_sparsity_out(int i) {
  switch (i) {
    case 0: return s2;
    default: return 0;
  }
}

int adjFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 22;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
